imported Jason Giedymin's newest version of the nginx init script

diff --git a/etc/init.d/nginx-init b/etc/init.d/nginx-init
--- a/etc/init.d/nginx-init
+++ b/etc/init.d/nginx-init
@@ -5,38 +5,38 @@
 # Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: nginx init.d dash script for Ubuntu <=9.10.
-# Description:       nginx init.d dash script for Ubuntu <=9.10.
+# Short-Description: nginx init.d dash script for Ubuntu or other *nix.
+# Description:       nginx init.d dash script for Ubuntu or other *nix.
 ### END INIT INFO
 #------------------------------------------------------------------------------
 # nginx - this Debian Almquist shell (dash) script, starts and stops the nginx
-#         daemon for ubuntu 9.10 and lesser version numbered releases.
+#         daemon for Ubuntu and other *nix releases.
 #
 # description:  Nginx is an HTTP(S) server, HTTP(S) reverse \
 #               proxy and IMAP/POP3 proxy server.  This \
-#		script will manage the initiation of the \
-#		server and it's process state.
+#               script will manage the initiation of the \
+#               server and it's process state.
 #
 # processname: nginx
 # config:      /usr/local/nginx/conf/nginx.conf
-# pidfile:     /acronymlabs/server/nginx.pid
+# pidfile:     /usr/local/nginx/logs/nginx.pid
 # Provides:    nginx
 #
 # Author:  Jason Giedymin
 #          <jason.giedymin AT gmail.com>.
 #
-# Version: 2.0 02-NOV-2009 jason.giedymin AT gmail.com
-# Notes: nginx init.d dash script for Ubuntu <=9.10.
+# Version: 3.0 22-APR-2013 jason.giedymin AT gmail.com
+# Notes: nginx init.d dash script for Ubuntu.
+# Tested with: Ubuntu 12.10, nginx-1.3.16
 #
 # This script's project home is:
-# 	http://code.google.com/p/nginx-init-ubuntu/
+#   http://github.com/JasonGiedymin/nginx-init-ubuntu
 #
 #------------------------------------------------------------------------------
 #                               MIT X11 License
 #------------------------------------------------------------------------------
 #
-# Copyright (c) 2009 Jason Giedymin, http://Amuxbit.com formerly
-#				     http://AcronymLabs.com
+# Copyright (c) 2008-2013 Jason Giedymin, http://jasongiedymin.com
 #
 # Permission is hereby granted, free of charge, to any person obtaining
 # a copy of this software and associated documentation files (the
@@ -67,24 +67,24 @@
 #                               Consts
 #------------------------------------------------------------------------------
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DAEMON=/usr/sbin/nginx
+DAEMON=/usr/local/nginx/sbin/nginx
 
 PS="nginx"
-PIDNAME="nginx"				#lets you do $PS-slave
-PIDFILE=$PIDNAME.pid                    #pid file
-PIDSPATH=/var/run
+PIDNAME="nginx"                     #lets you do $PS-slave
+PIDFILE=$PIDNAME.pid                #pid file
+PIDSPATH=/usr/local/nginx/logs      #default pid location, you should change it
 
 DESCRIPTION="Nginx Server..."
 
-RUNAS=root                              #user to run as
+RUNAS=root                          #user to run as
 
-SCRIPT_OK=0                             #ala error codes
-SCRIPT_ERROR=1                          #ala error codes
-TRUE=1                                  #boolean
-FALSE=0                                 #boolean
+SCRIPT_OK=0                         #ala error codes
+SCRIPT_ERROR=1                      #ala error codes
+TRUE=1                              #boolean
+FALSE=0                             #boolean
 
 lockfile=/var/lock/subsys/nginx
-NGINX_CONF_FILE="/etc/nginx/nginx.conf"
+NGINX_CONF_FILE="/usr/local/nginx/conf/nginx.conf"
 
 #------------------------------------------------------------------------------
 #                               Simple Tests
@@ -95,7 +95,7 @@ test -x $DAEMON || exit 0
 
 # Include nginx defaults if available
 if [ -f /etc/default/nginx ] ; then
-        . /etc/default/nginx
+    . /etc/default/nginx
 fi
 
 #set exit condition
@@ -106,207 +106,205 @@ fi
 #------------------------------------------------------------------------------
 
 setFilePerms(){
-
-        if [ -f $PIDSPATH/$PIDFILE ]; then
-                chmod 400 $PIDSPATH/$PIDFILE
-        fi
+    if [ -f $PIDSPATH/$PIDFILE ]; then
+        chmod 400 $PIDSPATH/$PIDFILE
+    fi
 }
 
 configtest() {
-	$DAEMON -t -c $NGINX_CONF_FILE
+    $DAEMON -t -c $NGINX_CONF_FILE
 }
 
 getPSCount() {
-	return `pgrep -f $PS | wc -l`
+    return `pgrep -f $PS | wc -l`
 }
 
 isRunning() {
-        if [ $1 ]; then
-                pidof_daemon $1
-                PID=$?
+    if [ $1 ]; then
+        pidof_daemon $1
+        PID=$?
 
-                if [ $PID -gt 0 ]; then
-                        return 1
-                else
-                        return 0
-                fi
+        if [ $PID -gt 0 ]; then
+            return 1
         else
-                pidof_daemon
-                PID=$?
-
-                if [ $PID -gt 0 ]; then
-                        return 1
-                else
-                        return 0
-                fi
+            return 0
         fi
+    else
+        pidof_daemon
+        PID=$?
+
+        if [ $PID -gt 0 ]; then
+            return 1
+        else
+            return 0
+        fi
+    fi
 }
 
 #courtesy of php-fpm
 wait_for_pid () {
-        try=0
+    try=0
 
-        while test $try -lt 35 ; do
+    while test $try -lt 35 ; do
+        case "$1" in
+            'created')
+            if [ -f "$2" ] ; then
+                try=''
+                break
+            fi
+            ;;
 
-                case "$1" in
-                        'created')
-                        if [ -f "$2" ] ; then
-                                try=''
-                                break
-                        fi
-                        ;;
+            'removed')
+            if [ ! -f "$2" ] ; then
+                try=''
+                break
+            fi
+            ;;
+        esac
 
-                        'removed')
-                        if [ ! -f "$2" ] ; then
-                                try=''
-                                break
-                        fi
-                        ;;
-                esac
-
-                #echo -n .
-                try=`expr $try + 1`
-                sleep 1
-        done
+        try=`expr $try + 1`
+        sleep 1
+    done
 }
 
 status(){
-	isRunning
-	isAlive=$?
+    isRunning
+    isAlive=$?
 
-	if [ "${isAlive}" -eq $TRUE ]; then
-                echo "$PIDNAME found running with processes:  `pidof $PS`"
-        else
-                echo "$PIDNAME is NOT running."
-        fi
-
-
+    if [ "${isAlive}" -eq $TRUE ]; then
+        echo "$PIDNAME found running with processes:  `pidof $PS`"
+    else
+        echo "$PIDNAME is NOT running."
+    fi
 }
 
 removePIDFile(){
-	if [ $1 ]; then
-                if [ -f $1 ]; then
-        	        rm -f $1
-	        fi
-        else
-		#Do default removal
-		if [ -f $PIDSPATH/$PIDFILE ]; then
-        	        rm -f $PIDSPATH/$PIDFILE
-	        fi
+    if [ $1 ]; then
+        if [ -f $1 ]; then
+            rm -f $1
         fi
+    else
+        #Do default removal
+        if [ -f $PIDSPATH/$PIDFILE ]; then
+            rm -f $PIDSPATH/$PIDFILE
+        fi
+    fi
 }
 
 start() {
-        log_daemon_msg "Starting $DESCRIPTION"
+    log_daemon_msg "Starting $DESCRIPTION"
 
-	isRunning
-	isAlive=$?
+    isRunning
+    isAlive=$?
 
-        if [ "${isAlive}" -eq $TRUE ]; then
-                log_end_msg $SCRIPT_ERROR
-        else
-                start-stop-daemon --start --quiet --chuid $RUNAS --pidfile $PIDSPATH/$PIDFILE --exec $DAEMON \
-                -- -c $NGINX_CONF_FILE
-                setFilePerms
-                log_end_msg $SCRIPT_OK
-        fi
+    if [ "${isAlive}" -eq $TRUE ]; then
+        log_end_msg $SCRIPT_ERROR
+    else
+        start-stop-daemon --start --quiet --chuid \
+        $RUNAS --pidfile $PIDSPATH/$PIDFILE --exec $DAEMON \
+        -- -c $NGINX_CONF_FILE
+        setFilePerms
+        log_end_msg $SCRIPT_OK
+    fi
 }
 
 stop() {
-	log_daemon_msg "Stopping $DESCRIPTION"
+    log_daemon_msg "Stopping $DESCRIPTION"
 
-	isRunning
-	isAlive=$?
-        if [ "${isAlive}" -eq $TRUE ]; then
-                start-stop-daemon --stop --quiet --pidfile $PIDSPATH/$PIDFILE
+    isRunning
+    isAlive=$?
 
-		wait_for_pid 'removed' $PIDSPATH/$PIDFILE
+    if [ "${isAlive}" -eq $TRUE ]; then
+        start-stop-daemon --stop --quiet --pidfile $PIDSPATH/$PIDFILE
 
-                if [ -n "$try" ] ; then
-                        log_end_msg $SCRIPT_ERROR
-                else
-                        removePIDFile
-	                log_end_msg $SCRIPT_OK
-                fi
+        wait_for_pid 'removed' $PIDSPATH/$PIDFILE
 
+        if [ -n "$try" ] ; then
+            log_end_msg $SCRIPT_ERROR
         else
-                log_end_msg $SCRIPT_ERROR
+            removePIDFile
+            log_end_msg $SCRIPT_OK
         fi
+    else
+        log_end_msg $SCRIPT_ERROR
+    fi
 }
 
 reload() {
-	configtest || return $?
+    configtest || return $?
 
-	log_daemon_msg "Reloading (via HUP) $DESCRIPTION"
+    log_daemon_msg "Reloading (via HUP) $DESCRIPTION"
 
-        isRunning
-        if [ $? -eq $TRUE ]; then
-		`killall -HUP $PS` #to be safe
+    isRunning
 
-                log_end_msg $SCRIPT_OK
-        else
-                log_end_msg $SCRIPT_ERROR
-        fi
+    if [ $? -eq $TRUE ]; then
+        `killall -HUP $PS` #to be safe
+        log_end_msg $SCRIPT_OK
+    else
+        log_end_msg $SCRIPT_ERROR
+    fi
 }
 
 quietupgrade() {
-	log_daemon_msg "Peforming Quiet Upgrade $DESCRIPTION"
+    log_daemon_msg "Peforming Quiet Upgrade $DESCRIPTION"
+
+    isRunning
+    isAlive=$?
+
+    if [ "${isAlive}" -eq $TRUE ]; then
+        kill -USR2 `cat $PIDSPATH/$PIDFILE`
+        kill -WINCH `cat $PIDSPATH/$PIDFILE.oldbin`
 
         isRunning
         isAlive=$?
+
         if [ "${isAlive}" -eq $TRUE ]; then
-		kill -USR2 `cat $PIDSPATH/$PIDFILE`
-		kill -WINCH `cat $PIDSPATH/$PIDFILE.oldbin`
-
-		isRunning
-		isAlive=$?
-		if [ "${isAlive}" -eq $TRUE ]; then
-			kill -QUIT `cat $PIDSPATH/$PIDFILE.oldbin`
-			wait_for_pid 'removed' $PIDSPATH/$PIDFILE.oldbin
+            kill -QUIT `cat $PIDSPATH/$PIDFILE.oldbin`
+            wait_for_pid 'removed' $PIDSPATH/$PIDFILE.oldbin
                         removePIDFile $PIDSPATH/$PIDFILE.oldbin
 
-			log_end_msg $SCRIPT_OK
-		else
-			log_end_msg $SCRIPT_ERROR
-
-			log_daemon_msg "ERROR! Reverting back to original $DESCRIPTION"
-
-			kill -HUP `cat $PIDSPATH/$PIDFILE`
-			kill -TERM `cat $PIDSPATH/$PIDFILE.oldbin`
-			kill -QUIT `cat $PIDSPATH/$PIDFILE.oldbin`
-
-			wait_for_pid 'removed' $PIDSPATH/$PIDFILE.oldbin
-                        removePIDFile $PIDSPATH/$PIDFILE.oldbin
-
-			log_end_msg $SCRIPT_ok
-		fi
+            log_end_msg $SCRIPT_OK
         else
-                log_end_msg $SCRIPT_ERROR
+            log_end_msg $SCRIPT_ERROR
+
+            log_daemon_msg "ERROR! Reverting back to original $DESCRIPTION"
+
+            kill -HUP `cat $PIDSPATH/$PIDFILE`
+            kill -TERM `cat $PIDSPATH/$PIDFILE.oldbin`
+            kill -QUIT `cat $PIDSPATH/$PIDFILE.oldbin`
+
+            wait_for_pid 'removed' $PIDSPATH/$PIDFILE.oldbin
+            removePIDFile $PIDSPATH/$PIDFILE.oldbin
+
+            log_end_msg $SCRIPT_ok
         fi
+    else
+            log_end_msg $SCRIPT_ERROR
+    fi
 }
 
 terminate() {
-        log_daemon_msg "Force terminating (via KILL) $DESCRIPTION"
+    log_daemon_msg "Force terminating (via KILL) $DESCRIPTION"
 
-	PIDS=`pidof $PS` || true
+    PIDS=`pidof $PS` || true
 
-	[ -e $PIDSPATH/$PIDFILE ] && PIDS2=`cat $PIDSPATH/$PIDFILE`
+    [ -e $PIDSPATH/$PIDFILE ] && PIDS2=`cat $PIDSPATH/$PIDFILE`
 
-	for i in $PIDS; do
-		if [ "$i" = "$PIDS2" ]; then
-	        	kill $i
-                        wait_for_pid 'removed' $PIDSPATH/$PIDFILE
-			removePIDFile
-		fi
-	done
+    for i in $PIDS; do
+        if [ "$i" = "$PIDS2" ]; then
+            kill $i
+            wait_for_pid 'removed' $PIDSPATH/$PIDFILE
+            removePIDFile
+        fi
+    done
 
-	log_end_msg $SCRIPT_OK
+    log_end_msg $SCRIPT_OK
 }
 
 destroy() {
-	log_daemon_msg "Force terminating and may include self (via KILLALL) $DESCRIPTION"
-	killall $PS -q >> /dev/null 2>&1
-	log_end_msg $SCRIPT_OK
+    log_daemon_msg "Force terminating and may include self (via KILLALL) $DESCRIPTION"
+    killall $PS -q >> /dev/null 2>&1
+    log_end_msg $SCRIPT_OK
 }
 
 pidof_daemon() {
@@ -319,45 +317,46 @@ pidof_daemon() {
             return 1
         fi
     done
+
     return 0
 }
 
 case "$1" in
-  start)
-	start
+    start)
+        start
         ;;
-  stop)
-	stop
+    stop)
+        stop
         ;;
-  restart|force-reload)
-	stop
-	sleep 1
-	start
+    restart|force-reload)
+        stop
+        sleep 1
+        start
         ;;
-  reload)
-	$1
-	;;
-  status)
-	status
-	;;
-  configtest)
+    reload)
         $1
         ;;
-  quietupgrade)
-	$1
-	;;
-  terminate)
-	$1
-	;;
-  destroy)
-	$1
-	;;
-  *)
-	FULLPATH=/etc/init.d/$PS
-	echo "Usage: $FULLPATH {start|stop|restart|force-reload|status|configtest|quietupgrade|terminate|destroy}"
-	echo "       The 'destroy' command should only be used as a last resort."
-	exit 1
-	;;
+    status)
+        status
+        ;;
+    configtest)
+        $1
+        ;;
+    quietupgrade)
+        $1
+        ;;
+    terminate)
+        $1
+        ;;
+    destroy)
+        $1
+        ;;
+    *)
+        FULLPATH=/etc/init.d/$PS
+        echo "Usage: $FULLPATH {start|stop|restart|force-reload|status|configtest|quietupgrade|terminate|destroy}"
+        echo "       The 'destroy' command should only be used as a last resort."
+        exit 1
+        ;;
 esac
 
 exit 0
